apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: vitrina
  name: vitrina
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vitrina
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: vitrina
    spec:
      containers:
        - args:
            - sbt
            - run
          image: nikitaromanoov/lab7_vitrina:latest
          name: vitrina
          resources: {}
          volumeMounts:
            - mountPath: /app/showcase
              name: app-volume
      restartPolicy: Always
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: app-volume
status: {}
