apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kmeans
  name: kmeans
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kmeans
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kmeans
    spec:
      containers:
        - args:
            - bash
            - -c
            - python src/train.py && ls /app/showcase
          image: nikitaromanoov/lab7_kmeans_with_spark:latest
          name: kmeans-with-spark
          ports:
            - containerPort: 4041
            - containerPort: 8887
          resources:
            limits:
              cpu: "4"
          volumeMounts:
            - mountPath: /app/showcase
              name: app-volume
      restartPolicy: Always
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: app-volume
status: {}
